
name: Run SDET UI Tests and Publish Report

on:

  workflow_dispatch:


  push:
    branches:
      - main
      - master


permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  run-tests:

    name: Run UI Tests and Generate Report

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable


      - name: Run Pytest with Allure
        run: pytest --alluredir=allure-results || true


      - name: Generate and Deploy Allure Report
        uses: peaceiris/actions-allure-report@v3
        with:

          github_token: ${{ secrets.GITHUB_TOKEN }}

          allure_results_path: allure-results
