name: Run SDET UI Tests and Publish Report

on:

  workflow_dispatch:


  push:
    branches:
      - task_ui


  pull_request:
    branches:
      - master


permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  run-ui-tests:
    name: Run UI Tests and Generate Report
    runs-on: ubuntu-latest
    steps:
      - name: "1. Checkout repository"
        uses: actions/checkout@v4

      - name: "2. Set up Python 3.10"
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: "3. Set up Java 17 for Allure"
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: "4. Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: "5. Run Pytest with Allure"
        continue-on-error: true
        run: python -m pytest --alluredir=allure-results

      - name: "6. Generate Allure Report"
        if: always()
        run: |
          # Скачиваем и распаковываем Allure CLI
          wget https://github.com/allure-framework/allure2/releases/download/2.29.0/allure-2.29.0.tgz
          tar -zxvf allure-2.29.0.tgz
          # Генерируем HTML-отчет в папку allure-report
          ./allure-2.29.0/bin/allure generate allure-results --clean -o allure-report

      - name: "7. Upload Allure Report Artifact"
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report