name: Run SDET UI Tests and Publish Report

on:

  workflow_dispatch:


  push:
    branches:
      - task_ui


  pull_request:
    branches:
      - master


permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  run-ui-tests:
    name: Run UI Tests and Publish Report
    runs-on: ubuntu-latest
    steps:
      - name: "1. Checkout repository"
        uses: actions/checkout@v4

      - name: "2. Set up Python 3.10"
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: "3. Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      

      - name: "4. Run Pytest with Allure"
        continue-on-error: true
        run: python -m pytest --alluredir=allure-results

      - name: "5. Generate and Deploy Allure Report to GitHub Pages"
        if: always()
        uses: peaceiris/actions-allure-report@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          allure_results_path: allure-results